
import { Metadata } from 'next';
import CardSection from './dashboard/sections/CardSection';

export const metadata: Metadata = {
	title: 'BW Send',
	description: 'Generated by BWSoft',
};

export default function Example() {
	

	return (
		<>
			<div className="flex w-full justify-center min-h-full">
				<div className="px-4 py-4 sm:px-6 lg:px-8">
					<section
						className="relative z-10 mx-auto max-w-md sm:max-w-3xl lg:max-w-7xl py-8"
						aria-labelledby="contact-heading"
					>
						<h2 className="sr-only" id="contact-heading">
							Acesse
						</h2>
						<div className="grid grid-cols-1 w-full max-w-[1100px] lg:grid-cols-2 gap-5 gap-y-20">
							<CardSection />
						</div>
					</section>
				</div>
			</div>
		</>
	);
}
